// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineMarketPlace.DataAccess;

namespace OnlineMarketPlace.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190601101830_OnlineMarketPlace-v3")]
    partial class OnlineMarketPlacev3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("key");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Coupons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<string>("code");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<double>("discount");

                    b.Property<bool>("freeShipping");

                    b.Property<string>("key");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Images", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<string>("alt");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("key");

                    b.Property<string>("path");

                    b.HasKey("id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.OrderCoupons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<int?>("couponid");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("key");

                    b.Property<int?>("orderid");

                    b.HasKey("id");

                    b.HasIndex("couponid");

                    b.HasIndex("orderid");

                    b.ToTable("OrderCoupons");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.OrderProducts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("key");

                    b.Property<int?>("orderid");

                    b.Property<int?>("productid");

                    b.Property<int>("quantity");

                    b.Property<double>("totalWeight");

                    b.HasKey("id");

                    b.HasIndex("orderid");

                    b.HasIndex("productid");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Orders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateDelivered");

                    b.Property<DateTime?>("dateShipped");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("key");

                    b.Property<int?>("shipperid");

                    b.Property<int?>("shippingAddressid");

                    b.Property<double>("totalFreight");

                    b.Property<double>("totalPrice");

                    b.Property<int?>("userid");

                    b.HasKey("id");

                    b.HasIndex("shipperid");

                    b.HasIndex("shippingAddressid");

                    b.HasIndex("userid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.ProductImages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<int?>("imageid");

                    b.Property<string>("key");

                    b.Property<int?>("productid");

                    b.HasKey("id");

                    b.HasIndex("imageid");

                    b.HasIndex("productid");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<int?>("categoryid");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("description");

                    b.Property<string>("key");

                    b.Property<string>("name");

                    b.Property<int>("quantityAvailable");

                    b.Property<double>("unitPrice");

                    b.Property<double>("unitWeight");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("key");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Shippers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<double?>("freightBase");

                    b.Property<double>("freightPerKilo");

                    b.Property<string>("key");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.ShippingAddresses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("key");

                    b.Property<int?>("userid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("ShippingAddresses");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime?>("dateUpdated");

                    b.Property<string>("eMail");

                    b.Property<string>("firstName");

                    b.Property<string>("key");

                    b.Property<string>("lastName");

                    b.Property<string>("password");

                    b.Property<int?>("roleid");

                    b.HasKey("id");

                    b.HasIndex("roleid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.OrderCoupons", b =>
                {
                    b.HasOne("OnlineMarketPlace.Domain.Tables.Coupons", "coupon")
                        .WithMany()
                        .HasForeignKey("couponid");

                    b.HasOne("OnlineMarketPlace.Domain.Tables.Orders", "order")
                        .WithMany()
                        .HasForeignKey("orderid");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.OrderProducts", b =>
                {
                    b.HasOne("OnlineMarketPlace.Domain.Tables.Orders", "order")
                        .WithMany()
                        .HasForeignKey("orderid");

                    b.HasOne("OnlineMarketPlace.Domain.Tables.Products", "product")
                        .WithMany()
                        .HasForeignKey("productid");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Orders", b =>
                {
                    b.HasOne("OnlineMarketPlace.Domain.Tables.Shippers", "shipper")
                        .WithMany()
                        .HasForeignKey("shipperid");

                    b.HasOne("OnlineMarketPlace.Domain.Tables.ShippingAddresses", "shippingAddress")
                        .WithMany()
                        .HasForeignKey("shippingAddressid");

                    b.HasOne("OnlineMarketPlace.Domain.Tables.Users", "user")
                        .WithMany()
                        .HasForeignKey("userid");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.ProductImages", b =>
                {
                    b.HasOne("OnlineMarketPlace.Domain.Tables.Images", "image")
                        .WithMany()
                        .HasForeignKey("imageid");

                    b.HasOne("OnlineMarketPlace.Domain.Tables.Products", "product")
                        .WithMany()
                        .HasForeignKey("productid");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Products", b =>
                {
                    b.HasOne("OnlineMarketPlace.Domain.Tables.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.ShippingAddresses", b =>
                {
                    b.HasOne("OnlineMarketPlace.Domain.Tables.Users", "user")
                        .WithMany("shippingAddresses")
                        .HasForeignKey("userid");
                });

            modelBuilder.Entity("OnlineMarketPlace.Domain.Tables.Users", b =>
                {
                    b.HasOne("OnlineMarketPlace.Domain.Tables.Roles", "role")
                        .WithMany()
                        .HasForeignKey("roleid");
                });
#pragma warning restore 612, 618
        }
    }
}
